[package]
name = "AOC_23"
version = "0.1.0"
edition = "2021"

[dependencies]
priority-queue = "1.3.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

